"""atricle poster type edit

Revision ID: 711dee988077
Revises: 93730406cdb4
Create Date: 2023-10-19 23:53:39.959377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711dee988077'
down_revision: Union[str, None] = '93730406cdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE articles ALTER COLUMN poster TYPE UUID USING poster::UUID')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE articles ALTER COLUMN poster TYPE VARCHAR(255) USING poster::VARCHAR(255)')
    # ### end Alembic commands ###
