"""files added

Revision ID: 93730406cdb4
Revises: 1eeabdc818dc
Create Date: 2023-10-19 22:58:35.611396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93730406cdb4'
down_revision: Union[str, None] = '1eeabdc818dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_uploaded', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('poster', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('articles', 'poster_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('poster_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('articles', 'poster')
    op.drop_table('files')
    # ### end Alembic commands ###
