from enum import Enum


class AccessTags(Enum):
    CAN_GET_PUBLIC_ARTICLES = "CAN_GET_PUBLIC_ARTICLES"
    CAN_GET_PUBLIC_COMMENTS = "CAN_GET_PUBLIC_COMMENTS"

    # User
    CAN_GET_SELF_ARTICLES = "CAN_GET_SELF_ARTICLES"
    CAN_UPDATE_SELF_ARTICLES = "CAN_UPDATE_SELF_ARTICLES"
    CAN_DELETE_SELF_ARTICLES = "CAN_DELETE_SELF_ARTICLES"
    CAN_CREATE_SELF_ARTICLES = "CAN_CREATE_SELF_ARTICLES"

    CAN_CREATE_COMMENT = "CAN_CREATE_COMMENT"
    CAN_UPDATE_SELF_COMMENT = "CAN_UPDATE_SELF_COMMENT"
    CAN_DELETE_SELF_COMMENT = "CAN_DELETE_SELF_COMMENT"

    CAN_GET_SELF_NOTIFICATIONS = "CAN_GET_SELF_NOTIFICATIONS"
    CAN_DELETE_SELF_NOTIFICATION = "CAN_DELETE_SELF_NOTIFICATION"

    # Admin
    CAN_GET_PRIVATE_ARTICLES = "CAN_GET_PRIVATE_ARTICLES"
    CAN_UPDATE_USER_ARTICLES = "CAN_UPDATE_USER_ARTICLES"
    CAN_DELETE_USER_ARTICLES = "CAN_DELETE_USER_ARTICLES"

    CAN_DELETE_USER_COMMENT = "CAN_DELETE_USER_COMMENT"
    CAN_UPDATE_USER_COMMENT = "CAN_UPDATE_USER_COMMENT"
    CAN_GET_DELETED_COMMENTS = "CAN_GET_DELETED_COMMENTS"
